service: AVA-HIVE-PROD-TODO
provider:
  name: aws
  runtime: nodejs16.x
  stage: prod
  region: ap-south-1
  memorySize: 128
  apiGateway:
    restApiId: xrdeyndm7e
    restApiRootResourceId: q3j6pmzvm0
functions:
  app:
    handler: src/app.lambdaHandler
    events:
      - http:
          path: /todos
          method: ANY
      - http:
          path: /todos/{proxy+}
          method: ANY
          cors: true
      - http:
          path: /tags
          method: ANY
      - http:
          path: /tags/{proxy+}
          method: ANY
          cors: true
