service: AVA-HIVE-PROD-TODO
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-2
  memorySize: 128
  apiGateway:
    restApiId: wqefm8ssja
    restApiRootResourceId: fp8vr4aezh
functions:
  app:
    handler: src/app.lambdaHandler
    events:
      - http:
          path: /todos
          method: ANY
      - http:
          path: /todos/{proxy+}
          method: ANY
          cors: true
      - http:
          path: /tags
          method: ANY
      - http:
          path: /tags/{proxy+}
          method: ANY
          cors: true
